name: Deploy to GitHub Pages

on:
  # workflow_dispatch: # 버튼 클릭으로 워크플로우 트리거
  push:
    branches:
      - master # master 브랜치 업데이트 시 트리거

permissions:
  pages: write # GitHub Pages 배포를 위한 권한
  id-token: write # GitHub OIDC 토큰 발급

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 클론
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm install

      # 4. 빌드 실행 (빌드 결과물 생성)
      - name: Build project
        env:
          GROOM_PHONE: ${{ vars.GROOM_PHONE }}
          GROOM_FATHER_PHONE: ${{ vars.GROOM_FATHER_PHONE }}
          BRIDE_PHONE: ${{ vars.BRIDE_PHONE }}
          BRIDE_FATHER_PHONE: ${{ vars.BRIDE_FATHER_PHONE }}
          BRIDE_MOTHER_PHONE: ${{ vars.BRIDE_MOTHER_PHONE }}
          NAVER_MAP_CLIENT_ID: ${{ secrets.NAVER_MAP_CLIENT_ID }}
          GROOM_ACCOUNT: ${{ vars.GROOM_ACCOUNT }}
          GROOM_FATHER_ACCOUNT: ${{ vars.GROOM_FATHER_ACCOUNT }}
          BRIDE_ACCOUNT: ${{ vars.BRIDE_ACCOUNT }}
          BRIDE_FATHER_ACCOUNT: ${{ vars.BRIDE_FATHER_ACCOUNT }}
          BRIDE_MOTHER_ACCOUNT: ${{ vars.BRIDE_MOTHER_ACCOUNT }}
        run: |
          echo "VITE_GROOM_PHONE=${GROOM_PHONE}" >> .env
          echo "VITE_GROOM_FATHER_PHONE=${GROOM_FATHER_PHONE}" >> .env
          echo "VITE_BRIDE_PHONE=${BRIDE_PHONE}" >> .env
          echo "VITE_BRIDE_FATHER_PHONE=${BRIDE_FATHER_PHONE}" >> .env
          echo "VITE_BRIDE_MOTHER_PHONE=${BRIDE_MOTHER_PHONE}" >> .env
          echo "VITE_NAVER_MAP_CLIENT_ID=${NAVER_MAP_CLIENT_ID}" >> .env
          echo "VITE_GROOM_ACCOUNT=${GROOM_ACCOUNT}" >> .env
          echo "VITE_GROOM_FATHER_ACCOUNT=${GROOM_FATHER_ACCOUNT}" >> .env
          echo "VITE_BRIDE_ACCOUNT=${BRIDE_ACCOUNT}" >> .env
          echo "VITE_BRIDE_FATHER_ACCOUNT=${BRIDE_FATHER_ACCOUNT}" >> .env
          echo "VITE_BRIDE_MOTHER_ACCOUNT=${BRIDE_MOTHER_ACCOUNT}" >> .env
          npm run build

      # 5. GitHub Pages로 직접 배포
      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs # 빌드 결과물이 저장된 폴더

      # 6. Pages 배포 트리거
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1