name: Deploy to GitHub Pages

on:
  workflow_dispatch: # 버튼 클릭으로 워크플로우 트리거

permissions:
  contents: write # GitHub Pages 배포를 위한 쓰기 권한 설정

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 클론
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm install

      # 4. 빌드 실행 (빌드 결과물 생성)
      - name: Build project
        env:
          GROOM_PHONE: ${{ secrets.GROOM_PHONE }}
          GROOM_FATHER_PHONE: ${{ secrets.GROOM_FATHER_PHONE }}
          BRIDE_PHONE: ${{ secrets.BRIDE_PHONE }}
          BRIDE_FATHER_PHONE: ${{ secrets.BRIDE_FATHER_PHONE }}
          BRIDE_MOTHER_PHONE: ${{ secrets.BRIDE_MOTHER_PHONE }}
        run: |
          echo "VITE_GROOM_PHONE=${GROOM_PHONE}" >> .env
          echo "VITE_GROOM_FATHER_PHONE=${GROOM_FATHER_PHONE}" >> .env
          echo "VITE_BRIDE_PHONE=${BRIDE_PHONE}" >> .env
          echo "VITE_BRIDE_FATHER_PHONE=${BRIDE_FATHER_PHONE}" >> .env
          echo "VITE_BRIDE_MOTHER_PHONE=${BRIDE_MOTHER_PHONE}" >> .env
          npm run build

      # 5. GitHub Pages로 배포 (브랜치 저장 없이 배포)
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # GitHub Pages에서 사용할 브랜치 (저장 X)
          folder: docs # 배포할 폴더 (빌드 결과물이 생성된 폴더)
          token: ${{ secrets.GITHUB_TOKEN }} # GitHub Actions 제공 기본 토큰

